# sampling rate [samples]
sr: 22050

# whether to use raw signal as an input
raw_signal: false
 
# stft | mel | mfcc
transformation: stft

#! stft parameters
# size of FFT, creates n_fft // 2 + 1 bins
n_fft: 1024
# length of hop between STFT windows
hop_length: 512

#! mel parameters (uses stft parameters)
# number of mel features
n_mels: 128
# frequency upper bound: int or null
f_max: 11000
# frequency lower bound
f_min: 0

#! mfcc parameters (uses stft and mel parameters)
# number of mfcc features
n_mfcc: 0

#! features post processing
# time masking and frequency masking augmentations for training
feature_augmentation: false
time_mask_param: null
freq_mask_param: null

# size of gaussian kernel and sigma e.g.: [5, 0.5]
gaussian_blur: false
gaussian_blur_kernel_size: 5
gaussian_blur_sigma: 0.5

# resize features
resize: false
# resize to size e.g.: [128, 128]
resize_size: [128, 128]

# zero mean, unit variance feature normalization:
# none | row-wise | column-wise | global
normalization: global

# zero mean, unit variance signal normalization
signal_normalization: false