# gpu number
cuda: 0
# learning rate
lr: 0.0001
# number of traing epochs
n_epochs: 200
# batch size
batch_size: 64
# number of workers
num_workers: 8
# training to validation ratio
split_ratio: 0.75
# use new offset after each epoch
use_offset: True
# offset length in sec
offset_length: 0.25
# number of classes to predict
num_classes: 50

# length of one hop in seconds
nn_hop_length: 6.0
# length of one window in seconds
window_length: 6.0

# list of neural network heads
heads: ['n_counts']