- 05_Mobius_aligned_RX100
- 05_iphone_aligned_RX100
- 06_Mobius_aligned_RX100
- 06_RX100
- 10_RX100
- 11_Mobius_aligned_RX100
- 12_Mobius_aligned_RX100
- 12_iphone_aligned_RX100
- 13_Mobius_aligned_RX100
- 13_RX100
- 14_Mobius_aligned_RX100
- 14_RX100
- 15_Mobius_aligned_RX100
- 15_RX100
- 16_Mobius_aligned_RX100
- 16_RX100
- 17_Mobius_aligned_RX100
- 17_RX100
- 17_iphone_aligned_RX100
- 18_Prazska_Mobius_aligned_RX100
- 18_Prazska_RX100
- 18_Prazska_iphone_aligned_RX100
- 19_Krocehlavska_RX100
- 19_Krocehlavska_iphone_aligned_RX100
- 20_Kovary_Mobius_aligned_RX100
- 20_Kovary_iphone_aligned_RX100
- 21_Videnska_Mobius_aligned_RX100
- 21_Videnska_iphone_aligned_RX100
- 22_Jesenicka_RX100
- 22_Jesenicka_iphone_aligned_RX100
- 23_KeZlatnikum_RX100
- 23_KeZlatnikum_iphone_aligned_RX100
- 24_Cernokostelecka_iphone_aligned_RX100
- 25_Hlavni_Mobius_aligned_RX100
- 25_Hlavni_RX100
- 25_Hlavni_iphone_aligned_RX100
- 27_Komoranska_Mobius_aligned_RX100
- 27_Komoranska_iphone_aligned_RX100
- 28_BrezanskeUdoli_Mobius_aligned_RX100
- 28_BrezanskeUdoli_iphone_aligned_RX100
- 30_RadotinskaS_iphone_aligned_RX100
- 31_RadotinskaJ2_Mobius_aligned_RX100
- 31_RadotinskaJ2_RX100
- 31_RadotinskaJ2_iphone_aligned_RX100
- 32_Cementarska_iphone_aligned_RX100
- 33_Vypadova_RX100
- 33_Vypadova_iphone_aligned_RX100
- 34_PrazskaDobrichovice_Mobius_aligned_RX100
- 34_PrazskaDobrichovice_RX100
- 34_PrazskaDobrichovice_iphone_aligned_RX100
- 35_Rovinska_RX100
- 35_Rovinska_iphone_aligned_RX100
- 36_Jesenicka_RX100
- 37_Prazska_Jircany_Mobius_aligned_RX100
- 37_Prazska_Jircany_RX100
- 38_Libusska_Mobius_aligned_RX100
- 38_Libusska_iphone_aligned_RX100
- 39_KPrehradam_Mobius_aligned_RX100
- 39_KPrehradam_RX100
- 39_KPrehradam_iphone_aligned_RX100
- 40_KeZlatnikum_Mobius_aligned_RX100
- 40_KeZlatnikum_RX100
- 40_KeZlatnikum_iphone_aligned_RX100
- 41_Dobrejovice_Mobius_aligned_RX100
- 41_Dobrejovice_RX100
- 41_Dobrejovice_iphone_aligned_RX100
- 42_RadotinskaJ2_Mobius_aligned_RX100
- 42_RadotinskaJ2_RX100
- 43_PrazskaDobrichovice_Mobius_aligned_RX100
- 43_PrazskaDobrichovice_RX100
- 44_Cementarska_Mobius_aligned_RX100
- 44_Cementarska_RX100
- - 45_RX100
  - 1
- - 46_RX100
  - 1
- - 46_iphonexs_aligned_RX100
  - 1
- - 47_Mobius_aligned_RX100
  - 1
- - 47_RX100
  - 1
- - 50_Mobius_aligned_RX100
  - 1
- - 51_RX100
  - 1
- - 51_Samsung_aligned_RX100
  - 1
- - 52_Samsung_aligned_RX100
  - 1
- - 53_Mobius_aligned_RX100
  - 1
- - 54_Samsung_aligned_RX100
  - 1
- - 55_Samsung_aligned_RX100
  - 1
- - 56_Mobius_aligned_RX100
  - 1
- - 56_RX100
  - 1
- - 56_Samsung_aligned_RX100
  - 1
- - 58_Samsung_aligned_RX100
  - 1
- - 59_Samsung_aligned_RX100
  - 1
- - 60_RX100
  - 1
- - 61_Mobius_aligned_RX100
  - 1
- - 61_Samsung_aligned_RX100
  - 1
- 20190819-Kutna Hora-L1-out-MVI_0007
- 20190819-Kutna Hora-L3-in-MVI_0005
- 20190819-Kutna Hora-L6-out-MVI_0017
- 20190819-Kutna Hora-L7-out-MVI_0032
- 20190819-Kutna Hora-L9-in-MVI_0043
- 20190819-Kutna Hora-L13-in-MVI_0006
- 20190819-Ricany-L2-in-MVI_0006
- 20190819-Ricany-L7-in-MVI_0008
- 20190819-Ricany-L8-in-MVI_0009
- - 62_Mobius_aligned_RX100
  - 1
- - 62_RX100
  - 1
- - 63_Samsung_aligned_RX100
  - 1
- - 64_Mobius_aligned_RX100
  - 1
- - 64_RX100
  - 1
- - 65_RX100
  - 1
- - 65_Samsung_aligned_RX100
  - 1
- - 66_RX100
  - 1
- - 68_Mobius_aligned_RX100
  - 1
- - 68_RX100
  - 1
- - 68_Samsung_aligned_RX100
  - 1
- - 69_Mobius_aligned_RX100
  - 1
- - 70_Mobius_aligned_RX100
  - 1
- - 70_Samsung_aligned_RX100
  - 1
- - 71_Mobius_aligned_RX100
  - 1
- - 71_RX100
  - 1
- - 71_Samsung_aligned_RX100
  - 1
