- 05_RX100
- 09_RX100
- 09_iphone_aligned_RX100
- 10_Mobius_aligned_RX100
- 12_RX100
- 13_iphone_aligned_RX100
- 16_iphone_aligned_RX100
- 19_Krocehlavska_Mobius_aligned_RX100
- 20_Kovary_RX100
- 22_Jesenicka_Mobius_aligned_RX100
- 23_KeZlatnikum_Mobius_aligned_RX100
- 24_Cernokostelecka_RX100
- 27_Komoranska_RX100
- 28_BrezanskeUdoli_RX100
- 29_KPrehradam_iphone_aligned_RX100
- 30_RadotinskaS_Mobius_aligned_RX100
- 32_Cementarska_Mobius_aligned_RX100
- 33_Vypadova_Mobius_aligned_RX100
- 35_Rovinska_Mobius_aligned_RX100
- 36_Jesenicka_iphone_aligned_RX100
- 37_Prazska_Jircany_iphone_aligned_RX100
- 38_Libusska_RX100
- - 45_Mobius_aligned_RX100
  - 1
- - 49_RX100
  - 1
- - 49_iphonexs_aligned_RX100
  - 1
- - 51_Mobius_aligned_RX100
  - 1
- - 52_RX100
  - 1
- - 54_Mobius_aligned_RX100
  - 1
- - 54_RX100
  - 1
- - 58_Mobius_aligned_RX100
  - 1
- - 58_RX100
  - 1
- 20190819-Kutna Hora-L14-out-MVI_0005
- 20190819-Ricany-L6-in-MVI_0008
- 20190819-Ricany-L6-out-MVI_0011
- 20190819-Ricany-L8-out-MVI_0013
- 20190819-Ricany-L9-in-MVI_0008
- 20190819-Ricany-L9-out-MVI_0011
- - 66_Samsung_aligned_RX100
  - 1
- - 67_RX100
  - 1
- - 70_RX100
  - 1
