

wandb_project: vehicle-audio-nn
wandb_entity: yermandy
wandb_tags: [classification]

output_name: test

lr: 0.0001
cuda: 0
n_epochs: 5
batch_size: 128
num_workers: 4

split_ratio: 0.75
n_trn_samples: -1
n_val_samples: -1

# length of the FFT window in samples
n_fft: 1024
# number of mels, i.e. rows in mel spectrogram
n_mels: 128
# hop length between samples for feature extractor
hop_length: 128
# sampling rate
sr: 44100
# length of one window in seconds
window_length: 6.0


use_offset: True
offset_length: 0.25
# none / row-wise / column-wise / global
normalization: global
num_classes: 50

testing_files:
  - 20190819-Kutna Hora-L4-out-MVI_0040

training_files:
  - 20190819-Kutna Hora-L4-out-MVI_0040

defaults:
  - _self_
  - dataset: dataset_26.11.2021
  # - training_files: dataset_26.11.2021