# @package _global_

# name of run
uuid: 000_${now:%d.%m.%y}_${now:%H-%M-%S}

seed: 42
splits: [0, 1, 2, 3, 4]
structured_predictor_splits: [0, 1, 2, 3, 4]
structured_predictor_regs: [1, 0.1, 0.01]
structured_predictor_heads: ['n_counts']

# ! will be filled in code
split: ...
root_uuid: ...

defaults:
  - _self_
  - wandb: wandb
  - testing_files: default
  - training_files: default
  - validation_files: default
  - features@_here_: default
  - model@_here_: default
  - structured_predictor: null
  - experiment: null