# @package _global_

# name of run
uuid: 000_${now:%d.%m.%y}_${now:%H-%M-%S}

seed: 42

# ! specify the following parameters in experiment
# List[Int] of splits for training the neural network
splits: ...
# List[Int] of splits for training the structured predictor
structured_predictor_splits: ...
# List[Float] of regularization values for structured predictor
structured_predictor_regs: ...
# List[String] of head names
structured_predictor_heads: ...

# ! will be filled in code
split: ...
root_uuid: ...

wandb_mode: online

defaults:
  - _self_
  - wandb: wandb
  - testing_files: default
  - training_files: default
  - validation_files: default
  - features@_here_: default
  - model@_here_: default
  - structured_predictor: null
  - svm_predictor: null
  - experiment: null