- 07_RX100
- 09_Mobius_aligned_RX100
- 10_iphone_aligned_RX100
- 11_RX100
- 11_iphone_aligned_RX100
- 15_iphone_aligned_RX100
- 21_Videnska_RX100
- 24_Cernokostelecka_Mobius_aligned_RX100
- 26_Novosibrinska_Mobius_aligned_RX100
- 26_Novosibrinska_RX100
- 26_Novosibrinska_iphone_aligned_RX100
- 29_KPrehradam_Mobius_aligned_RX100
- 29_KPrehradam_RX100
- 30_RadotinskaS_RX100
- 32_Cementarska_RX100
- 36_Jesenicka_Mobius_aligned_RX100
- - 45_iphonexs_aligned_RX100
  - 1
- - 46_Mobius_aligned_RX100
  - 1
- - 48_Mobius_aligned_RX100
  - 1
- - 48_RX100
  - 1
- - 48_iphonexs_aligned_RX100
  - 1
- - 49_Mobius_aligned_RX100
  - 1
- - 50_RX100
  - 1
- - 50_Samsung_aligned_RX100
  - 1
- - 52_Mobius_aligned_RX100
  - 1
- - 53_RX100
  - 1
- - 53_Samsung_aligned_RX100
  - 1
- - 55_RX100
  - 1
- - 59_RX100
  - 1
- - 60_Samsung_aligned_RX100
  - 1
- - 61_RX100
  - 1
- 20190819-Kutna Hora-L3-out-MVI_0008
- 20190819-Kutna Hora-L15-out-MVI_0012
- 20190819-Kutna Hora-L18-in-MVI_0030
- - 62_Samsung_aligned_RX100
  - 1
- - 63_Mobius_aligned_RX100
  - 1
- - 63_RX100
  - 1
- - 64_Samsung_aligned_RX100
  - 1
- - 67_Samsung_aligned_RX100
  - 1
- - 69_RX100
  - 1
